# Generated by Django 4.2.1 on 2023-06-03 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('tempo', models.CharField(max_length=100)),
                ('repetitions', models.CharField(max_length=100)),
                ('rest', models.CharField(max_length=100)),
                ('resistance', models.CharField(max_length=100)),
                ('sets', models.CharField(max_length=100)),
                ('fatigue_level', models.CharField(max_length=100)),
                ('instructions', models.TextField(max_length=250)),
                ('category', models.CharField(choices=[('C', 'Cervical'), ('T', 'Thoracic'), ('L', 'Lumbar'), ('S', 'Shoulders'), ('H', 'Hips'), ('K', 'Knees'), ('A', 'Ankles'), ('F', 'Feet'), ('O', 'Other')], default='C', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
