# Generated by Django 4.2.2 on 2023-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='embed_code',
            field=models.TextField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
