# Generated by Django 4.2.2 on 2023-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_exercise_url_exercise_embed_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='embed_code',
        ),
        migrations.AddField(
            model_name='exercise',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
